version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      labels: []
      schedule:
          interval: weekly
    - package-ecosystem: gradle
      directory: /
      labels: []
      schedule:
          interval: weekly
