name: CI

on:
    push:
        branches: [main]
    pull_request:

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: nschloe/action-cached-lfs-checkout@385a8ecc719e50b8c71af6ab01a624b486b7c3bc # v1.2.5
              with:
                  fetch-depth: 0
            - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
            - run: ./gradlew build

    build-docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  fetch-depth: 0
                  fetch-tags: true
                  persist-credentials: false
            - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
            - run: ./gradlew :mkdocsBuild
            - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
              with:
                  path: build/mkdocs

    check-format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  fetch-depth: 0
                  fetch-tags: true
                  persist-credentials: false
            - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
            - run: mise run check

    # stub to use as a "required" check on github
    all-good:
        needs: [build, check-format, build-docs]
        runs-on: ubuntu-latest
        steps:
            - run: echo 'All checks passed!'
