name: CI

on:
    push:
        branches: [main]
    pull_request:

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: nschloe/action-cached-lfs-checkout@v1
              with:
                  fetch-depth: 0
                  fetch-tags: true
            - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
            - run: ./gradlew build

    build-docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0
                  fetch-tags: true
                  persist-credentials: false
            - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
            - run: ./gradlew :mkdocsBuild
            - uses: actions/upload-pages-artifact@v4
              with:
                  path: build/mkdocs

    check-format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
              with:
                  fetch-depth: 0
                  fetch-tags: true
                  persist-credentials: false
            - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
            - run: mise run check

    # stub to use as a "required" check on github
    all-good:
        needs: [build, check-format, build-docs]
        runs-on: ubuntu-latest
        steps:
            - run: echo 'All checks passed!'
