name: opencode

on:
    issue_comment:
        types: [created]

jobs:
    opencode:
        if: |
            contains(github.event.comment.body, ' /oc') ||
            startsWith(github.event.comment.body, '/oc') ||
            contains(github.event.comment.body, ' /opencode') ||
            startsWith(github.event.comment.body, '/opencode')
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            pull-requests: read
            issues: read
        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0
                  fetch-tags: true
                  lfs: true
            - uses: actions/setup-java@v5
              with:
                  distribution: temurin
                  java-version: 21
            - uses: extractions/setup-just@v3
            - run: pip install pre-commit
            - uses: sst/opencode/github@latest
              env:
                  ZHIPU_API_KEY: ${{ secrets.ZHIPU_API_KEY }}
              with:
                  model: zai-coding-plan/glm-4.6
